# Generated by Django 3.0.3 on 2020-04-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200422_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='author',
            field=models.CharField(default='komari', max_length=100),
            preserve_default=False,
        ),
    ]
