# Generated by Django 3.0.3 on 2020-04-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todomodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='author_pk',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
