# Generated by Django 3.0.3 on 2020-04-25 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todomodel_author_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='end_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
