# Generated by Django 3.0.3 on 2020-04-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20200425_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='todomodel',
            name='duedate',
        ),
        migrations.RemoveField(
            model_name='todomodel',
            name='memo',
        ),
    ]
